# Generated by Django 5.1.1 on 2024-09-26 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nicafood',
            name='user',
        ),
    ]
