# Generated by Django 5.1.1 on 2024-09-20 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_age_user_country_user_first_last_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
