# Generated by Django 5.1.1 on 2024-10-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_nicafood_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='foodtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='nicafood',
            name='type',
            field=models.ManyToManyField(to='main.foodtype'),
        ),
    ]
