# Generated by Django 5.1.1 on 2024-09-20 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0003_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('lastname', models.CharField(max_length=40)),
                ('age', models.IntegerField(max_length=3)),
                ('gender', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=40)),
                ('cellphone', models.IntegerField(max_length=10)),
                ('procedence', models.CharField(max_length=40)),
                ('password', models.FloatField(max_length=50)),
            ],
        ),
    ]
