# Generated by Django 5.1.1 on 2024-10-19 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_foodtype_nicafood_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='nicafood',
            name='price',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
